# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
arr=np.random.uniform(0,20,28).reshape(4,7)
arr1= (arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(arr1)

[[0.7400839  0.54204412 0.2934563  0.61957783 0.03447946 0.29553154
  0.51839394]
 [0.56259383 0.32456757 0.17224637 0.69284791 0.77807961 0.89858827
  0.49753237]
 [0.39029106 0.00124013 0.         1.         0.04682947 0.25514605
  0.1442554 ]
 [0.37234069 0.99837733 0.69061792 0.1774941  0.09784896 0.41743832
  0.3953855 ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
axis=0
a=np.random.randint(0,10,80).reshape(8,10)
print(min(a.sum(axis-1)))
print(a.sum(axis-1))

22
[55 38 48 40 38 58 22 43]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

distance = np.linalg.norm(a - b)

print(distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)

X = -np.dot(inv_A, np.dot(C, inv_B))

print(X)

[[ 1.00000000e+00  2.44249065e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np 
doc=np.loadtxt('minutes_n_ingredients.csv',delimiter=",",skiprows=1,dtype=np.int32)
print(doc[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
import numpy as np 
doc=np.loadtxt('minutes_n_ingredients.csv',delimiter=",",skiprows=1,dtype=np.int32)
doc1=doc[:,1:]
print('сред. знач:',np.mean(doc1,axis=0),'min:', np.min(doc1,axis=0), 'max:', np.max(doc1,axis=0), 'медиана:', np.median(doc1,axis=0))

сред. знач: [2.16010017e+04 9.05528000e+00] min: [0 1] max: [2147483647         39] медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
print(doc[doc[:,1]<np.quantile(doc[:,1],0.75)])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
time_limit=doc.copy()
notzero=time_limit.copy()
mask= notzero[:,1]==0
zero_n=np.count_nonzero(mask)
notzero[:,1][mask]=1
print(zero_n)
print(notzero, end='\n')

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
unique_rec= np.unique(notzero[:,1:], axis=0).shape[0]
print(unique_rec, end='\n')

4183


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(notzero[:,2]), end='\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [2]:
import numpy as np 
doc=np.loadtxt('minutes_n_ingredients.csv',delimiter=",",skiprows=1,dtype=np.int32)
filter_doc=doc[doc[:,1]<=5]
print(filter_doc)

[[ 67660      5      6]
 [204134      5      3]
 [ 66842      2      4]
 ...
 [420725      5      3]
 [  4747      0      9]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [3]:
import numpy as np
doc = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)
#  среднего количества ингредиентов на одну минуту рецепта
sred_ingredients = doc[:, 1] / doc[:, 0]

max_ingredients = np.max(sred_ingredients)
print("Максимальное среднее количество ингредиентов на одну минуту рецепта:", max_ingredients)

Максимальное среднее количество ингредиентов на одну минуту рецепта: 8207.560747877866


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
import numpy as np
doc = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)

top100=np.argsort(doc[:,0])[-100:]
top100_recipes=doc[top100]

sr_ingredients= np.mean(top100_recipes[:, 2])
print(sr_ingredients) 




12.04


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
import numpy as np
doc = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)





11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [11]:
import numpy as np
doc = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)

sr_ingredients=np.mean(doc[:2])
mense_sr= doc[:2]<sr_ingredients
percent= 100*len(mense_sr)/len(mense_sr)
print(percent)



100.0


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.